root: true
env:
  browser: true
  jest: true
extends: ['standard-with-typescript', 'plugin:prettier/recommended']
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
ignorePatterns: ['dist', 'build']
